export const countryData = [
  {
    name: "Afghanistan",
    flag: "🇦🇫",
    initials: "AF",
    countryCode: "+93",
    continent: "Asia",
  },
  {
    name: "Åland Islands",
    flag: "🇦🇽",
    initials: "AX",
    countryCode: "+358",
    continent: "Europe",
  },
  {
    name: "Albania",
    flag: "🇦🇱",
    initials: "AL",
    countryCode: "+355",
    continent: "Europe",
  },
  {
    name: "Algeria",
    flag: "🇩🇿",
    initials: "DZ",
    countryCode: "+213",
    continent: "Africa",
  },
  {
    name: "American Samoa",
    flag: "🇦🇸",
    initials: "AS",
    countryCode: "+1-684",
    continent: "Oceania",
  },
  {
    name: "Andorra",
    flag: "🇦🇩",
    initials: "AD",
    countryCode: "+376",
    continent: "Europe",
  },
  {
    name: "Angola",
    flag: "🇦🇴",
    initials: "AO",
    countryCode: "+244",
    continent: "Africa",
  },
  {
    name: "Anguilla",
    flag: "🇦🇮",
    initials: "AI",
    countryCode: "+1-264",
    continent: "North America",
  },
  {
    name: "Antarctica",
    flag: "🇦🇶",
    initials: "AQ",
    countryCode: "+672",
    continent: "Antarctica",
  },
  {
    name: "Antigua and Barbuda",
    flag: "🇦🇬",
    initials: "AG",
    countryCode: "+1-268",
    continent: "North America",
  },
  {
    name: "Argentina",
    flag: "🇦🇷",
    initials: "AR",
    countryCode: "+54",
    continent: "South America",
  },
  {
    name: "Armenia",
    flag: "🇦🇲",
    initials: "AM",
    countryCode: "+374",
    continent: "Asia",
  },
  {
    name: "Aruba",
    flag: "🇦🇼",
    initials: "AW",
    countryCode: "+297",
    continent: "North America", // Geographically South America, politically often linked to North America/Caribbean
  },
  {
    name: "Australia",
    flag: "🇦🇺",
    initials: "AU",
    countryCode: "+61",
    continent: "Oceania",
  },
  {
    name: "Austria",
    flag: "🇦🇹",
    initials: "AT",
    countryCode: "+43",
    continent: "Europe",
  },
  {
    name: "Azerbaijan",
    flag: "🇦🇿",
    initials: "AZ",
    countryCode: "+994",
    continent: "Asia",
  },
  {
    name: "Bahamas",
    flag: "🇧🇸",
    initials: "BS",
    countryCode: "+1-242",
    continent: "North America",
  },
  {
    name: "Bahrain",
    flag: "🇧🇭",
    initials: "BH",
    countryCode: "+973",
    continent: "Asia",
  },
  {
    name: "Bangladesh",
    flag: "🇧🇩",
    initials: "BD",
    countryCode: "+880",
    continent: "Asia",
  },
  {
    name: "Barbados",
    flag: "🇧🇧",
    initials: "BB",
    countryCode: "+1-246",
    continent: "North America",
  },
  {
    name: "Belarus",
    flag: "🇧🇾",
    initials: "BY",
    countryCode: "+375",
    continent: "Europe",
  },
  {
    name: "Belgium",
    flag: "🇧🇪",
    initials: "BE",
    countryCode: "+32",
    continent: "Europe",
  },
  {
    name: "Belize",
    flag: "🇧🇿",
    initials: "BZ",
    countryCode: "+501",
    continent: "North America",
  },
  {
    name: "Benin",
    flag: "🇧🇯",
    initials: "BJ",
    countryCode: "+229",
    continent: "Africa",
  },
  {
    name: "Bermuda",
    flag: "🇧🇲",
    initials: "BM",
    countryCode: "+1-441",
    continent: "North America",
  },
  {
    name: "Bhutan",
    flag: "🇧🇹",
    initials: "BT",
    countryCode: "+975",
    continent: "Asia",
  },
  {
    name: "Bolivia",
    flag: "🇧🇴",
    initials: "BO",
    countryCode: "+591",
    continent: "South America",
  },
  {
    name: "Bonaire, Sint Eustatius and Saba",
    flag: "🇧🇶",
    initials: "BQ",
    countryCode: "+599",
    continent: "North America", // Geographically South America
  },
  {
    name: "Bosnia and Herzegovina",
    flag: "🇧🇦",
    initials: "BA",
    countryCode: "+387",
    continent: "Europe",
  },
  {
    name: "Botswana",
    flag: "🇧🇼",
    initials: "BW",
    countryCode: "+267",
    continent: "Africa",
  },
  {
    name: "Bouvet Island",
    flag: "🇧🇻",
    initials: "BV",
    countryCode: "+47", // Shared with Norway, uninhabited
    continent: "Antarctica",
  },
  {
    name: "Brazil",
    flag: "🇧🇷",
    initials: "BR",
    countryCode: "+55",
    continent: "South America",
  },
  {
    name: "British Indian Ocean Territory",
    flag: "🇮🇴",
    initials: "IO",
    countryCode: "+246",
    continent: "Asia", // Geographically Africa
  },
  {
    name: "British Virgin Islands",
    flag: "🇻🇬",
    initials: "VG",
    countryCode: "+1-284",
    continent: "North America",
  },
  {
    name: "Brunei",
    flag: "🇧🇳",
    initials: "BN",
    countryCode: "+673",
    continent: "Asia",
  },
  {
    name: "Bulgaria",
    flag: "🇧🇬",
    initials: "BG",
    countryCode: "+359",
    continent: "Europe",
  },
  {
    name: "Burkina Faso",
    flag: "🇧🇫",
    initials: "BF",
    countryCode: "+226",
    continent: "Africa",
  },
  {
    name: "Burundi",
    flag: "🇧🇮",
    initials: "BI",
    countryCode: "+257",
    continent: "Africa",
  },
  {
    name: "Cabo Verde", // Cape Verde
    flag: "🇨🇻",
    initials: "CV",
    countryCode: "+238",
    continent: "Africa",
  },
  {
    name: "Cambodia",
    flag: "🇰🇭",
    initials: "KH",
    countryCode: "+855",
    continent: "Asia",
  },
  {
    name: "Cameroon",
    flag: "🇨🇲",
    initials: "CM",
    countryCode: "+237",
    continent: "Africa",
  },
  {
    name: "Canada",
    flag: "🇨🇦",
    initials: "CA",
    countryCode: "+1",
    continent: "North America",
  },
  {
    name: "Cayman Islands",
    flag: "🇰🇾",
    initials: "KY",
    countryCode: "+1-345",
    continent: "North America",
  },
  {
    name: "Central African Republic",
    flag: "🇨🇫",
    initials: "CF",
    countryCode: "+236",
    continent: "Africa",
  },
  {
    name: "Chad",
    flag: "🇹🇩",
    initials: "TD",
    countryCode: "+235",
    continent: "Africa",
  },
  {
    name: "Chile",
    flag: "🇨🇱",
    initials: "CL",
    countryCode: "+56",
    continent: "South America",
  },
  {
    name: "China",
    flag: "🇨🇳",
    initials: "CN",
    countryCode: "+86",
    continent: "Asia",
  },
  {
    name: "Christmas Island",
    flag: "🇨🇽",
    initials: "CX",
    countryCode: "+61", // Shared with Australia
    continent: "Oceania", // Geographically Asia
  },
  {
    name: "Cocos (Keeling) Islands",
    flag: "🇨🇨",
    initials: "CC",
    countryCode: "+61", // Shared with Australia
    continent: "Oceania", // Geographically Asia
  },
  {
    name: "Colombia",
    flag: "🇨🇴",
    initials: "CO",
    countryCode: "+57",
    continent: "South America",
  },
  {
    name: "Comoros",
    flag: "🇰🇲",
    initials: "KM",
    countryCode: "+269",
    continent: "Africa",
  },
  {
    name: "Congo (Brazzaville)", // Republic of the Congo
    flag: "🇨🇬",
    initials: "CG",
    countryCode: "+242",
    continent: "Africa",
  },
  {
    name: "Congo (Kinshasa)", // Democratic Republic of the Congo
    flag: "🇨🇩",
    initials: "CD",
    countryCode: "+243",
    continent: "Africa",
  },
  {
    name: "Cook Islands",
    flag: "🇨🇰",
    initials: "CK",
    countryCode: "+682",
    continent: "Oceania",
  },
  {
    name: "Costa Rica",
    flag: "🇨🇷",
    initials: "CR",
    countryCode: "+506",
    continent: "North America",
  },
  {
    name: "Côte d'Ivoire", // Ivory Coast
    flag: "🇨🇮",
    initials: "CI",
    countryCode: "+225",
    continent: "Africa",
  },
  {
    name: "Croatia",
    flag: "🇭🇷",
    initials: "HR",
    countryCode: "+385",
    continent: "Europe",
  },
  {
    name: "Cuba",
    flag: "🇨🇺",
    initials: "CU",
    countryCode: "+53",
    continent: "North America",
  },
  {
    name: "Curaçao",
    flag: "🇨🇼",
    initials: "CW",
    countryCode: "+599", // Shared code element
    continent: "North America", // Geographically South America
  },
  {
    name: "Cyprus",
    flag: "🇨🇾",
    initials: "CY",
    countryCode: "+357",
    continent: "Europe", // Geographically Asia
  },
  {
    name: "Czech Republic",
    flag: "🇨🇿",
    initials: "CZ",
    countryCode: "+420",
    continent: "Europe",
  },
  {
    name: "Denmark",
    flag: "🇩🇰",
    initials: "DK",
    countryCode: "+45",
    continent: "Europe",
  },
  {
    name: "Djibouti",
    flag: "🇩🇯",
    initials: "DJ",
    countryCode: "+253",
    continent: "Africa",
  },
  {
    name: "Dominica",
    flag: "🇩🇲",
    initials: "DM",
    countryCode: "+1-767",
    continent: "North America",
  },
  {
    name: "Dominican Republic",
    flag: "🇩🇴",
    initials: "DO",
    countryCode: "+1-809", // +1-829, +1-849 also used
    continent: "North America",
  },
  {
    name: "Ecuador",
    flag: "🇪🇨",
    initials: "EC",
    countryCode: "+593",
    continent: "South America",
  },
  {
    name: "Egypt",
    flag: "🇪🇬",
    initials: "EG",
    countryCode: "+20",
    continent: "Africa", // Sinai peninsula is in Asia
  },
  {
    name: "El Salvador",
    flag: "🇸🇻",
    initials: "SV",
    countryCode: "+503",
    continent: "North America",
  },
  {
    name: "Equatorial Guinea",
    flag: "🇬🇶",
    initials: "GQ",
    countryCode: "+240",
    continent: "Africa",
  },
  {
    name: "Eritrea",
    flag: "🇪🇷",
    initials: "ER",
    countryCode: "+291",
    continent: "Africa",
  },
  {
    name: "Estonia",
    flag: "🇪🇪",
    initials: "EE",
    countryCode: "+372",
    continent: "Europe",
  },
  {
    name: "Eswatini", // formerly Swaziland
    flag: "🇸🇿",
    initials: "SZ",
    countryCode: "+268",
    continent: "Africa",
  },
  {
    name: "Ethiopia",
    flag: "🇪🇹",
    initials: "ET",
    countryCode: "+251",
    continent: "Africa",
  },
  {
    name: "Falkland Islands (Malvinas)",
    flag: "🇫🇰",
    initials: "FK",
    countryCode: "+500",
    continent: "South America",
  },
  {
    name: "Faroe Islands",
    flag: "🇫🇴",
    initials: "FO",
    countryCode: "+298",
    continent: "Europe",
  },
  {
    name: "Fiji",
    flag: "🇫🇯",
    initials: "FJ",
    countryCode: "+679",
    continent: "Oceania",
  },
  {
    name: "Finland",
    flag: "🇫🇮",
    initials: "FI",
    countryCode: "+358",
    continent: "Europe",
  },
  {
    name: "France",
    flag: "🇫🇷",
    initials: "FR",
    countryCode: "+33",
    continent: "Europe",
  },
  {
    name: "French Guiana",
    flag: "🇬🇫",
    initials: "GF",
    countryCode: "+594",
    continent: "South America",
  },
  {
    name: "French Polynesia",
    flag: "🇵🇫",
    initials: "PF",
    countryCode: "+689",
    continent: "Oceania",
  },
  {
    name: "French Southern Territories",
    flag: "🇹🇫",
    initials: "TF",
    countryCode: "+262", // Shared with Reunion, uninhabited except for researchers
    continent: "Antarctica", // Geographically diverse, HQ in Reunion (Africa)
  },
  {
    name: "Gabon",
    flag: "🇬🇦",
    initials: "GA",
    countryCode: "+241",
    continent: "Africa",
  },
  {
    name: "Gambia",
    flag: "🇬🇲",
    initials: "GM",
    countryCode: "+220",
    continent: "Africa",
  },
  {
    name: "Georgia",
    flag: "🇬🇪",
    initials: "GE",
    countryCode: "+995",
    continent: "Asia", // Sometimes considered Europe
  },
  {
    name: "Germany",
    flag: "🇩🇪",
    initials: "DE",
    countryCode: "+49",
    continent: "Europe",
  },
  {
    name: "Ghana",
    flag: "🇬🇭",
    initials: "GH",
    countryCode: "+233",
    continent: "Africa",
  },
  {
    name: "Gibraltar",
    flag: "🇬🇮",
    initials: "GI",
    countryCode: "+350",
    continent: "Europe",
  },
  {
    name: "Greece",
    flag: "🇬🇷",
    initials: "GR",
    countryCode: "+30",
    continent: "Europe",
  },
  {
    name: "Greenland",
    flag: "🇬🇱",
    initials: "GL",
    countryCode: "+299",
    continent: "North America",
  },
  {
    name: "Grenada",
    flag: "🇬🇩",
    initials: "GD",
    countryCode: "+1-473",
    continent: "North America",
  },
  {
    name: "Guadeloupe",
    flag: "🇬🇵",
    initials: "GP",
    countryCode: "+590",
    continent: "North America",
  },
  {
    name: "Guam",
    flag: "🇬🇺",
    initials: "GU",
    countryCode: "+1-671",
    continent: "Oceania",
  },
  {
    name: "Guatemala",
    flag: "🇬🇹",
    initials: "GT",
    countryCode: "+502",
    continent: "North America",
  },
  {
    name: "Guernsey",
    flag: "🇬🇬",
    initials: "GG",
    countryCode: "+44-1481", // Shares +44
    continent: "Europe",
  },
  {
    name: "Guinea",
    flag: "🇬🇳",
    initials: "GN",
    countryCode: "+224",
    continent: "Africa",
  },
  {
    name: "Guinea-Bissau",
    flag: "🇬🇼",
    initials: "GW",
    countryCode: "+245",
    continent: "Africa",
  },
  {
    name: "Guyana",
    flag: "🇬🇾",
    initials: "GY",
    countryCode: "+592",
    continent: "South America",
  },
  {
    name: "Haiti",
    flag: "🇭🇹",
    initials: "HT",
    countryCode: "+509",
    continent: "North America",
  },
  {
    name: "Heard Island and McDonald Islands",
    flag: "🇭🇲",
    initials: "HM",
    countryCode: "+672", // Shared code element, uninhabited
    continent: "Antarctica", // Geographically near Antarctica
  },
  {
    name: "Honduras",
    flag: "🇭🇳",
    initials: "HN",
    countryCode: "+504",
    continent: "North America",
  },
  {
    name: "Hong Kong",
    flag: "🇭🇰",
    initials: "HK",
    countryCode: "+852",
    continent: "Asia",
  },
  {
    name: "Hungary",
    flag: "🇭🇺",
    initials: "HU",
    countryCode: "+36",
    continent: "Europe",
  },
  {
    name: "Iceland",
    flag: "🇮🇸",
    initials: "IS",
    countryCode: "+354",
    continent: "Europe",
  },
  {
    name: "India",
    flag: "🇮🇳",
    initials: "IN",
    countryCode: "+91",
    continent: "Asia",
  },
  {
    name: "Indonesia",
    flag: "🇮🇩",
    initials: "ID",
    countryCode: "+62",
    continent: "Asia", // Some islands are in Oceania
  },
  {
    name: "Iran",
    flag: "🇮🇷",
    initials: "IR",
    countryCode: "+98",
    continent: "Asia",
  },
  {
    name: "Iraq",
    flag: "🇮🇶",
    initials: "IQ",
    countryCode: "+964",
    continent: "Asia",
  },
  {
    name: "Ireland",
    flag: "🇮🇪",
    initials: "IE",
    countryCode: "+353",
    continent: "Europe",
  },
  {
    name: "Isle of Man",
    flag: "🇮🇲",
    initials: "IM",
    countryCode: "+44-1624", // Shares +44
    continent: "Europe",
  },
  {
    name: "Israel",
    flag: "🇮🇱",
    initials: "IL",
    countryCode: "+972",
    continent: "Asia",
  },
  {
    name: "Italy",
    flag: "🇮🇹",
    initials: "IT",
    countryCode: "+39",
    continent: "Europe",
  },
  {
    name: "Jamaica",
    flag: "🇯🇲",
    initials: "JM",
    countryCode: "+1-876", // +1-658 also used
    continent: "North America",
  },
  {
    name: "Japan",
    flag: "🇯🇵",
    initials: "JP",
    countryCode: "+81",
    continent: "Asia",
  },
  {
    name: "Jersey",
    flag: "🇯🇪",
    initials: "JE",
    countryCode: "+44-1534", // Shares +44
    continent: "Europe",
  },
  {
    name: "Jordan",
    flag: "🇯🇴",
    initials: "JO",
    countryCode: "+962",
    continent: "Asia",
  },
  {
    name: "Kazakhstan",
    flag: "🇰🇿",
    initials: "KZ",
    countryCode: "+7", // Shared with Russia
    continent: "Asia", // Part is in Europe
  },
  {
    name: "Kenya",
    flag: "🇰🇪",
    initials: "KE",
    countryCode: "+254",
    continent: "Africa",
  },
  {
    name: "Kiribati",
    flag: "🇰🇮",
    initials: "KI",
    countryCode: "+686",
    continent: "Oceania",
  },
  {
    name: "Kosovo", // Status disputed
    flag: "🇽🇰",
    initials: "XK", // Provisional code
    countryCode: "+383",
    continent: "Europe",
  },
  {
    name: "Kuwait",
    flag: "🇰🇼",
    initials: "KW",
    countryCode: "+965",
    continent: "Asia",
  },
  {
    name: "Kyrgyzstan",
    flag: "🇰🇬",
    initials: "KG",
    countryCode: "+996",
    continent: "Asia",
  },
  {
    name: "Laos",
    flag: "🇱🇦",
    initials: "LA",
    countryCode: "+856",
    continent: "Asia",
  },
  {
    name: "Latvia",
    flag: "🇱🇻",
    initials: "LV",
    countryCode: "+371",
    continent: "Europe",
  },
  {
    name: "Lebanon",
    flag: "🇱🇧",
    initials: "LB",
    countryCode: "+961",
    continent: "Asia",
  },
  {
    name: "Lesotho",
    flag: "🇱🇸",
    initials: "LS",
    countryCode: "+266",
    continent: "Africa",
  },
  {
    name: "Liberia",
    flag: "🇱🇷",
    initials: "LR",
    countryCode: "+231",
    continent: "Africa",
  },
  {
    name: "Libya",
    flag: "🇱🇾",
    initials: "LY",
    countryCode: "+218",
    continent: "Africa",
  },
  {
    name: "Liechtenstein",
    flag: "🇱🇮",
    initials: "LI",
    countryCode: "+423",
    continent: "Europe",
  },
  {
    name: "Lithuania",
    flag: "🇱🇹",
    initials: "LT",
    countryCode: "+370",
    continent: "Europe",
  },
  {
    name: "Luxembourg",
    flag: "🇱🇺",
    initials: "LU",
    countryCode: "+352",
    continent: "Europe",
  },
  {
    name: "Macao",
    flag: "🇲🇴",
    initials: "MO",
    countryCode: "+853",
    continent: "Asia",
  },
  {
    name: "Madagascar",
    flag: "🇲🇬",
    initials: "MG",
    countryCode: "+261",
    continent: "Africa",
  },
  {
    name: "Malawi",
    flag: "🇲🇼",
    initials: "MW",
    countryCode: "+265",
    continent: "Africa",
  },
  {
    name: "Malaysia",
    flag: "🇲🇾",
    initials: "MY",
    countryCode: "+60",
    continent: "Asia",
  },
  {
    name: "Maldives",
    flag: "🇲🇻",
    initials: "MV",
    countryCode: "+960",
    continent: "Asia",
  },
  {
    name: "Mali",
    flag: "🇲🇱",
    initials: "ML",
    countryCode: "+223",
    continent: "Africa",
  },
  {
    name: "Malta",
    flag: "🇲🇹",
    initials: "MT",
    countryCode: "+356",
    continent: "Europe",
  },
  {
    name: "Marshall Islands",
    flag: "🇲🇭",
    initials: "MH",
    countryCode: "+692",
    continent: "Oceania",
  },
  {
    name: "Martinique",
    flag: "🇲🇶",
    initials: "MQ",
    countryCode: "+596",
    continent: "North America",
  },
  {
    name: "Mauritania",
    flag: "🇲🇷",
    initials: "MR",
    countryCode: "+222",
    continent: "Africa",
  },
  {
    name: "Mauritius",
    flag: "🇲🇺",
    initials: "MU",
    countryCode: "+230",
    continent: "Africa",
  },
  {
    name: "Mayotte",
    flag: "🇾🇹",
    initials: "YT",
    countryCode: "+262", // Shared with Reunion
    continent: "Africa",
  },
  {
    name: "Mexico",
    flag: "🇲🇽",
    initials: "MX",
    countryCode: "+52",
    continent: "North America",
  },
  {
    name: "Micronesia",
    flag: "🇫🇲",
    initials: "FM",
    countryCode: "+691",
    continent: "Oceania",
  },
  {
    name: "Moldova",
    flag: "🇲🇩",
    initials: "MD",
    countryCode: "+373",
    continent: "Europe",
  },
  {
    name: "Monaco",
    flag: "🇲🇨",
    initials: "MC",
    countryCode: "+377",
    continent: "Europe",
  },
  {
    name: "Mongolia",
    flag: "🇲🇳",
    initials: "MN",
    countryCode: "+976",
    continent: "Asia",
  },
  {
    name: "Montenegro",
    flag: "🇲🇪",
    initials: "ME",
    countryCode: "+382",
    continent: "Europe",
  },
  {
    name: "Montserrat",
    flag: "🇲🇸",
    initials: "MS",
    countryCode: "+1-664",
    continent: "North America",
  },
  {
    name: "Morocco",
    flag: "🇲🇦",
    initials: "MA",
    countryCode: "+212",
    continent: "Africa",
  },
  {
    name: "Mozambique",
    flag: "🇲🇿",
    initials: "MZ",
    countryCode: "+258",
    continent: "Africa",
  },
  {
    name: "Myanmar (Burma)",
    flag: "🇲🇲",
    initials: "MM",
    countryCode: "+95",
    continent: "Asia",
  },
  {
    name: "Namibia",
    flag: "🇳🇦",
    initials: "NA",
    countryCode: "+264",
    continent: "Africa",
  },
  {
    name: "Nauru",
    flag: "🇳🇷",
    initials: "NR",
    countryCode: "+674",
    continent: "Oceania",
  },
  {
    name: "Nepal",
    flag: "🇳🇵",
    initials: "NP",
    countryCode: "+977",
    continent: "Asia",
  },
  {
    name: "Netherlands",
    flag: "🇳🇱",
    initials: "NL",
    countryCode: "+31",
    continent: "Europe",
  },
  {
    name: "New Caledonia",
    flag: "🇳🇨",
    initials: "NC",
    countryCode: "+687",
    continent: "Oceania",
  },
  {
    name: "New Zealand",
    flag: "🇳🇿",
    initials: "NZ",
    countryCode: "+64",
    continent: "Oceania",
  },
  {
    name: "Nicaragua",
    flag: "🇳🇮",
    initials: "NI",
    countryCode: "+505",
    continent: "North America",
  },
  {
    name: "Niger",
    flag: "🇳🇪",
    initials: "NE",
    countryCode: "+227",
    continent: "Africa",
  },
  {
    name: "Nigeria",
    flag: "🇳🇬",
    initials: "NG",
    countryCode: "+234",
    continent: "Africa",
  },
  {
    name: "Niue",
    flag: "🇳🇺",
    initials: "NU",
    countryCode: "+683",
    continent: "Oceania",
  },
  {
    name: "Norfolk Island",
    flag: "🇳🇫",
    initials: "NF",
    countryCode: "+672", // Shared code element
    continent: "Oceania",
  },
  {
    name: "North Korea",
    flag: "🇰🇵",
    initials: "KP",
    countryCode: "+850",
    continent: "Asia",
  },
  {
    name: "North Macedonia", // formerly Macedonia
    flag: "🇲🇰",
    initials: "MK",
    countryCode: "+389",
    continent: "Europe",
  },
  {
    name: "Northern Mariana Islands",
    flag: "🇲🇵",
    initials: "MP",
    countryCode: "+1-670",
    continent: "Oceania",
  },
  {
    name: "Norway",
    flag: "🇳🇴",
    initials: "NO",
    countryCode: "+47",
    continent: "Europe",
  },
  {
    name: "Oman",
    flag: "🇴🇲",
    initials: "OM",
    countryCode: "+968",
    continent: "Asia",
  },
  {
    name: "Pakistan",
    flag: "🇵🇰",
    initials: "PK",
    countryCode: "+92",
    continent: "Asia",
  },
  {
    name: "Palau",
    flag: "🇵🇼",
    initials: "PW",
    countryCode: "+680",
    continent: "Oceania",
  },
  {
    name: "Palestine",
    flag: "🇵🇸",
    initials: "PS",
    countryCode: "+970",
    continent: "Asia",
  },
  {
    name: "Panama",
    flag: "🇵🇦",
    initials: "PA",
    countryCode: "+507",
    continent: "North America", // Can be considered transcontinental with South America
  },
  {
    name: "Papua New Guinea",
    flag: "🇵🇬",
    initials: "PG",
    countryCode: "+675",
    continent: "Oceania",
  },
  {
    name: "Paraguay",
    flag: "🇵🇾",
    initials: "PY",
    countryCode: "+595",
    continent: "South America",
  },
  {
    name: "Peru",
    flag: "🇵🇪",
    initials: "PE",
    countryCode: "+51",
    continent: "South America",
  },
  {
    name: "Philippines",
    flag: "🇵🇭",
    initials: "PH",
    countryCode: "+63",
    continent: "Asia",
  },
  {
    name: "Pitcairn Islands",
    flag: "🇵🇳",
    initials: "PN",
    countryCode: "+64", // Shared with New Zealand (unofficial +872)
    continent: "Oceania",
  },
  {
    name: "Poland",
    flag: "🇵🇱",
    initials: "PL",
    countryCode: "+48",
    continent: "Europe",
  },
  {
    name: "Portugal",
    flag: "🇵🇹",
    initials: "PT",
    countryCode: "+351",
    continent: "Europe",
  },
  {
    name: "Puerto Rico",
    flag: "🇵🇷",
    initials: "PR",
    countryCode: "+1-787", // +1-939 also used
    continent: "North America",
  },
  {
    name: "Qatar",
    flag: "🇶🇦",
    initials: "QA",
    countryCode: "+974",
    continent: "Asia",
  },
  {
    name: "Réunion",
    flag: "🇷🇪",
    initials: "RE",
    countryCode: "+262",
    continent: "Africa",
  },
  {
    name: "Romania",
    flag: "🇷🇴",
    initials: "RO",
    countryCode: "+40",
    continent: "Europe",
  },
  {
    name: "Russia",
    flag: "🇷🇺",
    initials: "RU",
    countryCode: "+7",
    continent: "Europe", // Spans Europe and Asia
  },
  {
    name: "Rwanda",
    flag: "🇷🇼",
    initials: "RW",
    countryCode: "+250",
    continent: "Africa",
  },
  {
    name: "Saint Barthélemy",
    flag: "🇧🇱",
    initials: "BL",
    countryCode: "+590", // Shared with Guadeloupe
    continent: "North America",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    flag: "🇸🇭",
    initials: "SH",
    countryCode: "+290", // (+247 for Ascension)
    continent: "Africa",
  },
  {
    name: "Saint Kitts and Nevis",
    flag: "🇰🇳",
    initials: "KN",
    countryCode: "+1-869",
    continent: "North America",
  },
  {
    name: "Saint Lucia",
    flag: "🇱🇨",
    initials: "LC",
    countryCode: "+1-758",
    continent: "North America",
  },
  {
    name: "Saint Martin", // French part
    flag: "🇲🇫",
    initials: "MF",
    countryCode: "+590", // Shared with Guadeloupe
    continent: "North America",
  },
  {
    name: "Saint Pierre and Miquelon",
    flag: "🇵🇲",
    initials: "PM",
    countryCode: "+508",
    continent: "North America",
  },
  {
    name: "Saint Vincent and the Grenadines",
    flag: "🇻🇨",
    initials: "VC",
    countryCode: "+1-784",
    continent: "North America",
  },
  {
    name: "Samoa",
    flag: "🇼🇸",
    initials: "WS",
    countryCode: "+685",
    continent: "Oceania",
  },
  {
    name: "San Marino",
    flag: "🇸🇲",
    initials: "SM",
    countryCode: "+378",
    continent: "Europe",
  },
  {
    name: "Sao Tome and Principe",
    flag: "🇸🇹",
    initials: "ST",
    countryCode: "+239",
    continent: "Africa",
  },
  {
    name: "Saudi Arabia",
    flag: "🇸🇦",
    initials: "SA",
    countryCode: "+966",
    continent: "Asia",
  },
  {
    name: "Senegal",
    flag: "🇸🇳",
    initials: "SN",
    countryCode: "+221",
    continent: "Africa",
  },
  {
    name: "Serbia",
    flag: "🇷🇸",
    initials: "RS",
    countryCode: "+381",
    continent: "Europe",
  },
  {
    name: "Seychelles",
    flag: "🇸🇨",
    initials: "SC",
    countryCode: "+248",
    continent: "Africa",
  },
  {
    name: "Sierra Leone",
    flag: "🇸🇱",
    initials: "SL",
    countryCode: "+232",
    continent: "Africa",
  },
  {
    name: "Singapore",
    flag: "🇸🇬",
    initials: "SG",
    countryCode: "+65",
    continent: "Asia",
  },
  {
    name: "Sint Maarten", // Dutch part
    flag: "🇸🇽",
    initials: "SX",
    countryCode: "+1-721",
    continent: "North America",
  },
  {
    name: "Slovakia",
    flag: "🇸🇰",
    initials: "SK",
    countryCode: "+421",
    continent: "Europe",
  },
  {
    name: "Slovenia",
    flag: "🇸🇮",
    initials: "SI",
    countryCode: "+386",
    continent: "Europe",
  },
  {
    name: "Solomon Islands",
    flag: "🇸🇧",
    initials: "SB",
    countryCode: "+677",
    continent: "Oceania",
  },
  {
    name: "Somalia",
    flag: "🇸🇴",
    initials: "SO",
    countryCode: "+252",
    continent: "Africa",
  },
  {
    name: "South Africa",
    flag: "🇿🇦",
    initials: "ZA",
    countryCode: "+27",
    continent: "Africa",
  },
  {
    name: "South Georgia and the South Sandwich Islands",
    flag: "🇬🇸",
    initials: "GS",
    countryCode: "+500", // Shared with Falklands, uninhabited except researchers
    continent: "Antarctica", // Geographically near Antarctica
  },
  {
    name: "South Korea",
    flag: "🇰🇷",
    initials: "KR",
    countryCode: "+82",
    continent: "Asia",
  },
  {
    name: "South Sudan",
    flag: "🇸🇸",
    initials: "SS",
    countryCode: "+211",
    continent: "Africa",
  },
  {
    name: "Spain",
    flag: "🇪🇸",
    initials: "ES",
    countryCode: "+34",
    continent: "Europe", // Has territories in Africa
  },
  {
    name: "Sri Lanka",
    flag: "🇱🇰",
    initials: "LK",
    countryCode: "+94",
    continent: "Asia",
  },
  {
    name: "Sudan",
    flag: "🇸🇩",
    initials: "SD",
    countryCode: "+249",
    continent: "Africa",
  },
  {
    name: "Suriname",
    flag: "🇸🇷",
    initials: "SR",
    countryCode: "+597",
    continent: "South America",
  },
  {
    name: "Svalbard and Jan Mayen",
    flag: "🇸🇯",
    initials: "SJ",
    countryCode: "+47", // Shared with Norway
    continent: "Europe",
  },
  {
    name: "Sweden",
    flag: "🇸🇪",
    initials: "SE",
    countryCode: "+46",
    continent: "Europe",
  },
  {
    name: "Switzerland",
    flag: "🇨🇭",
    initials: "CH",
    countryCode: "+41",
    continent: "Europe",
  },
  {
    name: "Syria",
    flag: "🇸🇾",
    initials: "SY",
    countryCode: "+963",
    continent: "Asia",
  },
  {
    name: "Taiwan",
    flag: "🇹🇼",
    initials: "TW",
    countryCode: "+886",
    continent: "Asia",
  },
  {
    name: "Tajikistan",
    flag: "🇹🇯",
    initials: "TJ",
    countryCode: "+992",
    continent: "Asia",
  },
  {
    name: "Tanzania",
    flag: "🇹🇿",
    initials: "TZ",
    countryCode: "+255",
    continent: "Africa",
  },
  {
    name: "Thailand",
    flag: "🇹🇭",
    initials: "TH",
    countryCode: "+66",
    continent: "Asia",
  },
  {
    name: "Timor-Leste", // East Timor
    flag: "🇹🇱",
    initials: "TL",
    countryCode: "+670",
    continent: "Asia", // Sometimes considered Oceania
  },
  {
    name: "Togo",
    flag: "🇹🇬",
    initials: "TG",
    countryCode: "+228",
    continent: "Africa",
  },
  {
    name: "Tokelau",
    flag: "🇹🇰",
    initials: "TK",
    countryCode: "+690",
    continent: "Oceania",
  },
  {
    name: "Tonga",
    flag: "🇹🇴",
    initials: "TO",
    countryCode: "+676",
    continent: "Oceania",
  },
  {
    name: "Trinidad and Tobago",
    flag: "🇹🇹",
    initials: "TT",
    countryCode: "+1-868",
    continent: "North America", // Geographically South America
  },
  {
    name: "Tunisia",
    flag: "🇹🇳",
    initials: "TN",
    countryCode: "+216",
    continent: "Africa",
  },
  {
    name: "Turkey",
    flag: "🇹🇷",
    initials: "TR",
    countryCode: "+90",
    continent: "Asia", // Spans Asia and Europe
  },
  {
    name: "Turkmenistan",
    flag: "🇹🇲",
    initials: "TM",
    countryCode: "+993",
    continent: "Asia",
  },
  {
    name: "Turks and Caicos Islands",
    flag: "🇹🇨",
    initials: "TC",
    countryCode: "+1-649",
    continent: "North America",
  },
  {
    name: "Tuvalu",
    flag: "🇹🇻",
    initials: "TV",
    countryCode: "+688",
    continent: "Oceania",
  },
  {
    name: "Uganda",
    flag: "🇺🇬",
    initials: "UG",
    countryCode: "+256",
    continent: "Africa",
  },
  {
    name: "Ukraine",
    flag: "🇺🇦",
    initials: "UA",
    countryCode: "+380",
    continent: "Europe",
  },
  {
    name: "United Arab Emirates",
    flag: "🇦🇪",
    initials: "AE",
    countryCode: "+971",
    continent: "Asia",
  },
  {
    name: "United Kingdom",
    flag: "🇬🇧",
    initials: "GB",
    countryCode: "+44",
    continent: "Europe",
  },
  {
    name: "United States",
    flag: "🇺🇸",
    initials: "US",
    countryCode: "+1",
    continent: "North America",
  },
  {
    name: "United States Minor Outlying Islands",
    flag: "🇺🇲", // Often uses US flag
    initials: "UM",
    countryCode: "+1", // Generally via US codes (e.g., +1-808 for some)
    continent: "Oceania", // Most are in Oceania
  },
  {
    name: "Uruguay",
    flag: "🇺🇾",
    initials: "UY",
    countryCode: "+598",
    continent: "South America",
  },
  {
    name: "US Virgin Islands",
    flag: "🇻🇮",
    initials: "VI",
    countryCode: "+1-340",
    continent: "North America",
  },
  {
    name: "Uzbekistan",
    flag: "🇺🇿",
    initials: "UZ",
    countryCode: "+998",
    continent: "Asia",
  },
  {
    name: "Vanuatu",
    flag: "🇻🇺",
    initials: "VU",
    countryCode: "+678",
    continent: "Oceania",
  },
  {
    name: "Vatican City", // Holy See
    flag: "🇻🇦",
    initials: "VA",
    countryCode: "+379", // Technically assigned, often +39 (Italy) used
    continent: "Europe",
  },
  {
    name: "Venezuela",
    flag: "🇻🇪",
    initials: "VE",
    countryCode: "+58",
    continent: "South America",
  },
  {
    name: "Vietnam",
    flag: "🇻🇳",
    initials: "VN",
    countryCode: "+84",
    continent: "Asia",
  },
  {
    name: "Wallis and Futuna",
    flag: "🇼🇫",
    initials: "WF",
    countryCode: "+681",
    continent: "Oceania",
  },
  {
    name: "Western Sahara", // Status disputed
    flag: "🇪🇭",
    initials: "EH",
    countryCode: "+212", // Often uses Morocco's code
    continent: "Africa",
  },
  {
    name: "Yemen",
    flag: "🇾🇪",
    initials: "YE",
    countryCode: "+967",
    continent: "Asia",
  },
  {
    name: "Zambia",
    flag: "🇿🇲",
    initials: "ZM",
    countryCode: "+260",
    continent: "Africa",
  },
  {
    name: "Zimbabwe",
    flag: "🇿🇼",
    initials: "ZW",
    countryCode: "+263",
    continent: "Africa",
  },
];
