export const campaigns = [
  {
    id: "e1c67c12-a9f6-47f6-9466-5e3e3b0ab501",
    status: "Live",
    preferences: {
      id: "9d71c3f4-38b9-44ec-8f4b-30c50e3d981c",
      videoStyle: ["Unboxing", "Review"],
      videosPerCreator: 2,
      videoDuration: 45,
      showFace: false,
      videoFormat: "square",
      socialChannels: ["YouTube Shorts"],
      collaborationType: [],
      campaignObjective: "Product Awareness",
      contentLanguages: "en",
    },
    products: [
      {
        id: "product1",
        productImages: [
          {
            id: 1,
            url: "http://res.cloudinary.com/dqjnaukdk/image/upload/v1743773452/1cdbd0a3-03d8-4cda-bdbb-d7dde1eb4ab4/products/gb4ureocip8mmhjt8vzl.jpg",
          },
        ],
        category: null,
        name: "Smart Fitness Band",
        description: "Track your workouts and health metrics with ease.",
        features: null,
        specifications: null,
        price: "120.00",
        discountPrice: null,
        currency: "USD",
        stockQuantity: 100,
        barcode: null,
        availabilityStatus: "IN_STOCK",
        productVideo: null,
        productManualUrl: "https://example.com/manual.pdf",
        productManualText:
          "Use this band to monitor your vitals during exercises.",
        affiliateUrl: null,
        createdBy: "creator1",
        isActive: true,
        createdAt: "2025-04-01T10:00:00Z",
        updatedAt: "2025-04-01T10:00:00Z",
      },
    ],
    services: [],
    collaborators: [],
    numberOfInfluencers: 3,
    title: "Smart Fit Spring Launch",
    description: "Promote our newest smart fitness wearable.",
    briefTitle: "Smart Fitness for Everyone",
    briefDescription:
      "Showcase how this band makes fitness smarter and easier.",
    startDate: "2025-04-01",
    endDate: "2025-04-20",
    brandId: "brand-123",
    exampleVideoUrl: "https://example.com/demo1",
    createdAt: "2025-04-01T10:00:00Z",
    coverImage: 1,
  },
  {
    id: "f6c14b64-2e3a-4175-91ed-6b7b827d18b1",
    status: "Live",
    preferences: {
      id: "2f91a0b4-59ea-4b0f-ae6a-1fdac6c6372d",
      videoStyle: ["Behind the scenes"],
      videosPerCreator: 1,
      videoDuration: 30,
      showFace: true,
      videoFormat: "vertical",
      socialChannels: ["Instagram Reels"],
      collaborationType: [],
      campaignObjective: "Brand Introduction",
      contentLanguages: "en",
    },
    products: [
      {
        id: "product2",
        productImages: [
          {
            id: 2,
            url: "http://res.cloudinary.com/dqjnaukdk/image/upload/v1743770978/1cdbd0a3-03d8-4cda-bdbb-d7dde1eb4ab4/products/acypajplqjdgg0bku0bo.jpg",
          },
        ],
        category: null,
        name: "Physican Fitness",
        description: "Join the revolution in fitness content creation.",
        features: null,
        specifications: null,
        price: "1500.00",
        discountPrice: null,
        currency: "USD",
        stockQuantity: 50,
        barcode: null,
        availabilityStatus: "IN_STOCK",
        productVideo: null,
        productManualUrl: "https://www.physicanfit.com/guide",
        productManualText: "Get started with our creator fitness journey.",
        affiliateUrl: null,
        createdBy: "creator2",
        isActive: true,
        createdAt: "2025-04-01T12:00:00Z",
        updatedAt: "2025-04-01T12:00:00Z",
      },
    ],
    services: [],
    collaborators: [],
    numberOfInfluencers: 2,
    title: "Physican Creator Campaign",
    description: "Let fitness enthusiasts explore Physican gear.",
    briefTitle: "Get Fit, Get Famous",
    briefDescription: "Show your gym routine using Physican.",
    startDate: "2025-04-05",
    endDate: "2025-04-30",
    brandId: "brand-234",
    exampleVideoUrl: "https://example.com/demo2",
    createdAt: "2025-04-02T09:30:00Z",
    coverImage: 2,
  },
  {
    id: "a5ddcfef-bd19-42b3-9b6a-69cbad2486d4",
    status: "Live",
    preferences: {
      id: "84f2ff59-4d9b-4f36-b033-88fc33a30c89",
      videoStyle: ["How To"],
      videosPerCreator: 3,
      videoDuration: 90,
      showFace: true,
      videoFormat: "horizontal",
      socialChannels: ["X Posts"],
      collaborationType: [],
      campaignObjective: "Education",
      contentLanguages: "en,fr",
    },
    products: [
      {
        id: "product3",
        productImages: [
          {
            id: 3,
            url: "http://res.cloudinary.com/dqjnaukdk/image/upload/v1743773452/1cdbd0a3-03d8-4cda-bdbb-d7dde1eb4ab4/products/gb4ureocip8mmhjt8vzl.jpg",
          },
        ],
        category: null,
        name: "Digital Notepad",
        description: "Create, edit, and share notes on the go.",
        features: null,
        specifications: null,
        price: "500.00",
        discountPrice: null,
        currency: "USD",
        stockQuantity: 80,
        barcode: null,
        availabilityStatus: "IN_STOCK",
        productVideo: null,
        productManualUrl: "https://example.com/notepad-manual",
        productManualText: "User-friendly instructions for getting started.",
        affiliateUrl: null,
        createdBy: "creator3",
        isActive: true,
        createdAt: "2025-04-03T14:00:00Z",
        updatedAt: "2025-04-03T14:00:00Z",
      },
    ],
    services: [],
    collaborators: [],
    numberOfInfluencers: 4,
    title: "Note Like a Pro",
    description: "Demonstrate productivity with our smart notepad.",
    briefTitle: "Smart Notes",
    briefDescription: "Help your audience improve study or work productivity.",
    startDate: "2025-04-03",
    endDate: "2025-04-28",
    brandId: "brand-345",
    exampleVideoUrl: "https://example.com/demo3",
    createdAt: "2025-04-03T14:00:00Z",
    coverImage: 3,
  },
  {
    id: "3f5d82c0-2386-4b35-a3f1-c8b31f3cd5f3",
    status: "Live",
    preferences: {
      id: "aaea344e-f36d-49be-ae95-d6f6d4dfed53",
      videoStyle: ["Review"],
      videosPerCreator: 2,
      videoDuration: 60,
      showFace: true,
      videoFormat: "vertical",
      socialChannels: ["Instagram Reels", "X Posts"],
      collaborationType: [],
      campaignObjective: "Conversions",
      contentLanguages: "en,es",
    },
    products: [
      {
        id: "product4",
        productImages: [
          {
            id: 4,
            url: "http://res.cloudinary.com/dqjnaukdk/image/upload/v1743770978/1cdbd0a3-03d8-4cda-bdbb-d7dde1eb4ab4/products/acypajplqjdgg0bku0bo.jpg",
          },
        ],
        category: null,
        name: "Keto Protein Shake",
        description: "A delicious protein blend perfect for keto diets.",
        features: null,
        specifications: null,
        price: "75.00",
        discountPrice: null,
        currency: "USD",
        stockQuantity: 150,
        barcode: null,
        availabilityStatus: "IN_STOCK",
        productVideo: null,
        productManualUrl: "https://example.com/keto-guide",
        productManualText: "Mix with water or milk and enjoy after workouts.",
        affiliateUrl: null,
        createdBy: "creator4",
        isActive: true,
        createdAt: "2025-04-04T11:00:00Z",
        updatedAt: "2025-04-04T11:00:00Z",
      },
    ],
    services: [],
    collaborators: [],
    numberOfInfluencers: 5,
    title: "Keto Shake Challenge",
    description: "Share your keto journey with our new protein shake.",
    briefTitle: "Fuel Your Keto Goals",
    briefDescription: "Tasty and powerful — get fit the keto way.",
    startDate: "2025-04-04",
    endDate: "2025-04-30",
    brandId: "brand-456",
    exampleVideoUrl: "https://example.com/demo4",
    createdAt: "2025-04-04T11:00:00Z",
    coverImage: 4,
  },
  {
    id: "cb1e6631-61b6-4c17-bcad-d1fe5db03bc3",
    status: "Live",
    preferences: {
      id: "27b8eec3-4e0e-420b-871e-cfa6e3cb59d2",
      videoStyle: ["Up to the creator"],
      videosPerCreator: 1,
      videoDuration: 15,
      showFace: false,
      videoFormat: "square",
      socialChannels: ["Instagram Stories"],
      collaborationType: [],
      campaignObjective: "Brand Recall",
      contentLanguages: "en",
    },
    products: [
      {
        id: "product5",
        productImages: [
          {
            id: 5,
            url: "http://res.cloudinary.com/dqjnaukdk/image/upload/v1743773452/1cdbd0a3-03d8-4cda-bdbb-d7dde1eb4ab4/products/gb4ureocip8mmhjt8vzl.jpg",
          },
        ],
        category: null,
        name: "Eco-Friendly Toothbrush",
        description: "Clean teeth, clean planet. 100% biodegradable.",
        features: null,
        specifications: null,
        price: "10.00",
        discountPrice: null,
        currency: "USD",
        stockQuantity: 300,
        barcode: null,
        availabilityStatus: "IN_STOCK",
        productVideo: null,
        productManualUrl: "https://example.com/eco-guide",
        productManualText: "Use daily, dispose responsibly.",
        affiliateUrl: null,
        createdBy: "creator5",
        isActive: true,
        createdAt: "2025-04-05T09:00:00Z",
        updatedAt: "2025-04-05T09:00:00Z",
      },
    ],
    services: [],
    collaborators: [],
    numberOfInfluencers: 10,
    title: "EcoBrush Social Campaign",
    description: "Make the switch to a greener smile.",
    briefTitle: "Eco-Friendly Smile",
    briefDescription: "Promote a sustainable alternative to plastic brushes.",
    startDate: "2025-04-05",
    endDate: "2025-04-25",
    brandId: "brand-567",
    exampleVideoUrl: "https://example.com/demo5",
    createdAt: "2025-04-05T09:00:00Z",
    coverImage: 5,
  },
];
