export const influencerData = [
    { id: 1, name: 'Beauty TikTok Influencers in Colorado Springs' },
    { id: 2, name: 'Influencers for Beauty in Kansas City on Instagram' },
    { id: 3, name: 'Influencers for Beauty in Colorado Springs on Instagram' },
    { id: 4, name: 'Influencers for Beauty in Mesa on Instagram' },
    { id: 5, name: 'Fitness Influencers in Miami' },
    { id: 6, name: 'Tech Reviewers on YouTube in San Francisco' },
    { id: 7, name: 'Travel Vloggers in New York City' },
    { id: 8, name: 'Food Bloggers in Chicago' },
    { id: 9, name: 'Gaming Streamers on Twitch in Seattle' },
    { id: 10, name: 'Fashion Influencers in Los Angeles' },
    { id: 11, name: 'Photography Influencers in Denver' },
    { id: 12, name: 'Lifestyle Influencers in Austin' },
    { id: 13, name: 'Parenting Bloggers in Houston' },
    { id: 14, name: 'Pet Influencers on Instagram' },
    { id: 15, name: 'DIY and Craft Influencers in Nashville' },
    { id: 16, name: 'Science Communicators on YouTube' },
    { id: 17, name: 'Book Reviewers on TikTok' },
    { id: 18, name: 'Entrepreneur Influencers in Silicon Valley' },
    { id: 19, name: 'Motivational Speakers on Instagram' },
    { id: 20, name: 'Health & Wellness Coaches in San Diego' },
    { id: 21, name: 'Car Enthusiasts on YouTube' },
    { id: 22, name: 'Music Critics on Twitter' },
    { id: 23, name: 'Sustainable Living Influencers' },
    { id: 24, name: 'Personal Finance Influencers in New York' },
    { id: 25, name: 'Comedy Content Creators on TikTok' },
    { id: 26, name: 'Luxury Lifestyle Influencers' },
    { id: 27, name: 'Digital Artists on Instagram' },
    { id: 28, name: 'Home Decor Influencers on Pinterest' },
    { id: 29, name: 'Gadget Reviewers in Silicon Valley' },
    { id: 30, name: 'Minimalist Lifestyle Bloggers' },
    { id: 31, name: 'Indie Game Developers on Twitter' },
    { id: 32, name: 'Movie Reviewers on YouTube' },
    { id: 33, name: 'Self-Improvement Coaches' },
    { id: 34, name: 'Outdoor Adventure Influencers' },
    { id: 35, name: 'Street Style Fashion Influencers' },
    { id: 36, name: 'Luxury Travel Bloggers' },
    { id: 37, name: 'Tattoo Artists on Instagram' },
    { id: 38, name: 'Wedding Planners on TikTok' },
    { id: 39, name: 'Mental Health Advocates on Instagram' },
    { id: 40, name: 'Skincare Experts on YouTube' },
    { id: 41, name: 'Tech Startups Influencers in Boston' },
    { id: 42, name: 'Vegan Food Influencers in Portland' },
    { id: 43, name: 'Eco-Friendly Living Influencers' },
    { id: 44, name: 'Photography Gear Reviewers on YouTube' },
    { id: 45, name: 'Street Photographers on Instagram' },
    { id: 46, name: 'College Student Influencers on TikTok' },
    { id: 47, name: 'Productivity Coaches on YouTube' },
    { id: 48, name: 'Luxury Watch Reviewers' },
    { id: 49, name: 'Interior Designers on Instagram' },
    { id: 50, name: 'Freelance Writers and Bloggers' },
    { id: 51, name: 'Anime and Manga Reviewers' },
    { id: 52, name: 'Handmade Jewelry Designers' },
    { id: 53, name: 'Streetwear Fashion Influencers' },
    { id: 54, name: 'Outdoor Survival Experts on YouTube' },
    { id: 55, name: 'History Buffs and Educators on Instagram' },
    { id: 56, name: 'RV and Van Life Travelers on YouTube' },
    { id: 57, name: 'Budget Travelers and Backpackers' },
    { id: 58, name: 'Digital Marketing Influencers' },
    { id: 59, name: 'Blockchain and Crypto Experts' },
    { id: 60, name: 'Home Bakers and Pastry Chefs' },
    { id: 61, name: 'Extreme Sports Athletes on Instagram' },
    { id: 62, name: 'Luxury Real Estate Influencers' },
    { id: 63, name: 'Space and Astronomy Enthusiasts' },
    { id: 64, name: 'Science Fiction Book Bloggers' },
    { id: 65, name: 'ASMR Creators on YouTube' },
    { id: 66, name: 'Handmade Crafts and Etsy Sellers' },
    { id: 67, name: 'Sustainable Fashion Influencers' },
    { id: 68, name: 'Custom Sneaker Designers' },
    { id: 69, name: 'Sneaker Collectors on Instagram' },
    { id: 70, name: 'Local Farmers and Organic Food Influencers' },
    { id: 71, name: 'Meditation and Mindfulness Coaches' },
    { id: 72, name: 'Language Learning Experts' },
    { id: 73, name: 'Calligraphy and Handwriting Artists' },
    { id: 74, name: 'Workout and Fitness Trainers' },
    { id: 75, name: 'Pilates and Yoga Influencers' },
    { id: 76, name: 'K-Pop Fans and Reviewers' },
    { id: 77, name: 'Tattoo Art Critics and Collectors' },
    { id: 78, name: 'Self-Defense and Martial Arts Coaches' },
    { id: 79, name: 'Horse Riding and Equestrian Influencers' },
    { id: 80, name: 'AI and Robotics Enthusiasts' }
];
